const { useState, useEffect } = React;

const SUPABASE_URL = "https://mmmrxjzpdmvurwevlsuq.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tbXJ4anpwZG12dXJ3ZXZsc3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NTYwNzcsImV4cCI6MjA4ODUzMjA3N30.bH4gbtN-q65kgHr2xbkmCrBMdn6L055e7MXvY_H1s6Q";
const sb = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

// -- DATA CACHE -----------------------------------------------------------------
const _cache = {};
const cached = async (key, fn, ttl = 30000) => {
  const now = Date.now();
  if (_cache[key] && now - _cache[key].ts < ttl) return _cache[key].data;
  const data = await fn();
  _cache[key] = { data, ts: now };
  return data;
};
const invalidate = (prefix) => {
  Object.keys(_cache).forEach(k => { if (k.startsWith(prefix)) delete _cache[k]; });
};


async function hashPassword(password) {
  const msgBuffer = new TextEncoder().encode(password + "soccerhq_salt_2024");
  const hashBuffer = await crypto.subtle.digest("SHA-256", msgBuffer);
  return Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, "0")).join("");
}

const phases = [
  { id: 0, title: "SPRING BREAK", subtitle: "Technical Foundation", weeks: "Week 1 — Travel Week", color: "var(--cyan)",
    focus: "No field. No gym. No partner. Pure ball mechanics — this week builds the technical foundation everything else sits on.",
    gym: [{ day: "Every Day", sessions: [{ name: "Bodyweight Conditioning", details: "Jump squats 4×15, lateral bounds 3×10 each side, explosive lunges 3×10, single leg calf raises 3×20. No equipment." }, { name: "Core", details: "Plank 3×45s, Dead Bug 3×10, V-sits 3×15, hollow body hold 3×30s. Every night before bed." }] }],
    field: [{ name: "Ball Striking Mechanics (30 min)", details: "Inside foot: lock ankle, toe out, strike center. Driven shot: approach at angle, plant foot beside ball, laces through center. Curl: strike inside-bottom quarter with laces for bend. Chip: stab underneath with stiff ankle. 20 reps each technique daily." }, { name: "Ball Spin Control (20 min)", details: "Topspin: strike above center → ball dips. Backspin: strike below center → ball floats. Sidespin: strike left or right of center → ball curves. Practice each deliberately, feel the difference." }, { name: "Ball Mastery Solo (20 min)", details: "Inside rolls, outside rolls, toe taps, V-pulls, scissors, step-overs — both feet. Log juggling record every day and beat it." }, { name: "First Touch Wall Work (20 min)", details: "Throw against wall, control dead in one touch — inside, outside, chest, thigh, laces. Both feet. 100 reps each surface." }],
    mental: "Watch Pirlo, Iniesta, and Xavi on YouTube. Search 'Pirlo through balls compilation' and 'Xavi passing masterclass.' Watch their body position before they receive — see how they already know where it's going before it arrives." },
  { id: 1, title: "PHASE 1", subtitle: "Foundation", weeks: "Weeks 2–4", color: "var(--cyan)",
    focus: "Build base fitness, ball comfort, and fundamental mechanics solo. Every drill works alone — wall, cones, open space.",
    gym: [{ day: "Mon / Wed / Fri", sessions: [{ name: "Explosive Lower Body", details: "Squats 4×8, Romanian Deadlifts 3×10, Box Jumps 4×6, Lateral Bounds 3×10 each side" }, { name: "Core Stability", details: "Plank 3×45s, Dead Bug 3×10, Pallof Press 3×12, Copenhagen Plank 3×20s" }] }, { day: "Tue / Thu", sessions: [{ name: "Conditioning", details: "20 min tempo run at 70% effort — building your aerobic base for 90 minutes on a field." }] }],
    field: [{ name: "Wall Passing — Solo (25 min)", details: "200 reps each foot. Lock ankle, follow through to target. Start 3m away, move back as accuracy builds." }, { name: "Shooting at a Target — Solo (25 min)", details: "Set up a target on a wall or fence. Alternate feet every 5 shots. Strike through center with laces. Log makes vs attempts." }, { name: "First Touch Control — Solo (20 min)", details: "Throw ball against wall, kill it dead in one touch. Inside, outside, chest, thigh, laces. Both feet. 100 reps each surface." }],
    mental: "Watch 1 game per week. Don't watch the ball. Watch one midfielder the entire game. Track their movement OFF the ball." },
  { id: 2, title: "PHASE 2", subtitle: "Sharpness", weeks: "Weeks 5–7", color: "var(--gold)",
    focus: "Increase intensity. Combine skills. Add fatigue to every drill. Solo work only.",
    gym: [{ day: "Mon / Wed / Fri", sessions: [{ name: "Power & Speed", details: "Bulgarian Split Squats 4×8, Single Leg RDL 3×10, Sprint Intervals 8×30m, Lateral Shuffle to Sprint 6×" }, { name: "Core + Rotational Power", details: "Rotational Med Ball Slam 4×8, Cable Woodchops 3×12, L-Sit Hold 3×20s" }] }, { day: "Tue / Thu", sessions: [{ name: "Interval Conditioning", details: "8×200m at 85% effort, 90s rest between. Builds specific fitness for repeated sprints in a game." }] }],
    field: [{ name: "Sprint → Shoot Sequence (25 min)", details: "Sprint 30m, arrive at ball, shoot at target immediately. No rest between sprint and shot. 10 reps each foot." }, { name: "Dribble Course (20 min)", details: "6 cones, 1m apart. Dribble through with inside/outside touches, both feet. Add shot at end. Time yourself and beat it." }, { name: "Curved Shot Practice (20 min)", details: "Strike inside-bottom quarter with laces for curl. Aim at target 15–20m away. 20 reps each foot daily." }],
    mental: "Study defensive structures. Search 'how to break a 4-4-2' and 'midfielder positioning between the lines.'" },
  { id: 3, title: "PHASE 3", subtitle: "Domination", weeks: "Weeks 8–11", color: "var(--red)",
    focus: "Game speed. Reading space. Becoming the most dangerous player. Get into pickup games.",
    gym: [{ day: "Mon / Wed", sessions: [{ name: "Maintain Strength", details: "Squats 3×5 heavy, RDL 3×6, Box Jumps 3×5. Maintaining now — field work is priority." }] }, { day: "Tue / Thu / Sat", sessions: [{ name: "Game Condition Fitness", details: "4×4 min at 90% intensity, 2 min rest. Mirrors actual game bursts." }] }],
    field: [{ name: "Decision Speed (25 min)", details: "Cone course, multiple exit options. Decide direction before you arrive. Two touches max. One touch when possible." }, { name: "Turn and Strike (20 min)", details: "Ball against wall, receive with back to wall, turn and shoot. Cruyff turn, inside hook, drop shoulder. Pick 2 and own them." }, { name: "Pickup Games", details: "Find games. Compete. Read the field before the ball comes. Play the pass before you receive it in your mind." }],
    mental: "5 minutes visualization before every session. See yourself on the TSA field. Read the play before it happens. Be the most dangerous person without needing to score." },
];

const bibleChapters = [
  { id: "ball", title: "The Ball", icon: "⚽", subtitle: "Physics, Spin & Striking", sections: [
    { title: "The Magnus Effect — Why The Ball Curves", content: "Every curved ball in soccer is the Magnus Effect in action. When a spinning ball moves through air, its rotation drags air around it. On one side airflow speeds up, on the other it slows down. The pressure difference pushes the ball toward the low-pressure side.\n\nThe key rule: a ball curves in the direction it's spinning.\n— Clockwise spin → curves right\n— Counterclockwise spin → curves left\n— Topspin (forward rotation) → dips down\n— Backspin (backward rotation) → floats, travels farther\n\nThe slower the ball travels, the more it curves. Speed reduces the effect." },
    { title: "The Knuckleball — No Spin", content: "Strike the ball with minimal spin and it becomes unpredictable. Without spin, airflow changes constantly as the panel seams rotate. The ball flutters, dips, and moves laterally without warning.\n\nHow to do it: Strike through the dead center of the ball with your laces, follow through stiff and straight. Minimal ankle snap.\n\nUse case: Long range free kicks, shots from outside the box. Ronaldo and Pirlo built careers on this." },
    { title: "Topspin — The Dipping Shot", content: "Topspin makes the ball dip faster than gravity alone.\n\nHow to create topspin:\n— Approach at a slight angle (30 degrees)\n— Plant foot slightly ahead of and beside the ball\n— Strike slightly above center with your laces\n— Keep your body over the ball — lean forward\n— The follow-through goes DOWN, not forward\n\nCommon mistake: Leaning back causes backspin and a ballooning shot. Get your body over the ball." },
    { title: "Backspin — The Chip & Float", content: "Backspin creates lift and a floating effect. Essential for chips over a goalkeeper and lofted through balls.\n\nHow to create backspin:\n— Stab underneath the ball with a stiff ankle\n— Shorter, sharper contact — don't follow through\n— Strike the bottom quarter of the ball\n\nThe chip: Same but more exaggerated. Knife under the ball, quick flick. Used to lob a rushing goalkeeper.\n\nNote: Backspin reduces forward speed. Use for precision, not power." },
    { title: "Sidespin — The Curl", content: "Sidespin bends free kicks around walls and curls crosses into dangerous areas.\n\nFor a right-footed player:\n— Strike the LEFT side with inside of foot → curves left to right (inswinging)\n— Strike the RIGHT side with outside of foot → curves right to left (outswinging)\n\nHow to curl with inside of foot:\n— Approach from the left\n— Plant foot pointing at target\n— Strike the inside-left quarter of the ball\n— Follow through across your body\n\nMore off-center = more curl but less power. Find the balance." },
    { title: "The Driven Shot — Power & Accuracy", content: "The bread and butter shot.\n\nMechanics:\n1. Approach at 30–45 degree angle\n2. Plant foot beside ball, toes pointing at target\n3. Lock your ankle — foot pointed down, firm\n4. Strike through the CENTER with laces\n5. Body OVER the ball — don't lean back\n6. Follow through toward target — leg swings high\n\nPower comes from hip rotation and knee snap. Your leg is the whip. Your locked ankle is the tip." },
    { title: "The Inside Pass — Accuracy First", content: "The foundation of everything.\n\nMechanics:\n1. Point standing foot at the target\n2. Open kicking foot out — toe pointed sideways\n3. Lock your ankle\n4. Strike through the CENTER with the flat inside surface\n5. Follow through toward the target\n\nWall drill: 200 reps each foot daily. Lock ankle, follow through, move target back as accuracy builds." },
  ]},
  { id: "formations", title: "Formations", icon: "📋", subtitle: "Shapes, Systems & How To Break Them", sections: [
    { title: "How To Read A Formation", content: "Formations are listed back to front, goalkeeper excluded.\n4-3-3 = 4 defenders, 3 midfielders, 3 forwards.\n\nBut formations are starting shapes. In possession a 4-3-3 becomes a 3-5-2. Out of possession a 4-2-3-1 becomes a 4-4-2.\n\nNumbers and roles:\n— #4, #5: Center backs\n— #2, #3: Fullbacks\n— #6: Defensive midfielder (holds, screens)\n— #8: Box-to-box midfielder\n— #10: Attacking midfielder / playmaker\n— #7, #11: Wingers\n— #9: Striker" },
    { title: "4-4-2 — The Classic", content: "Four defenders. Four midfielders. Two strikers.\n\nStrengths: Simple structure, two strikers, solid defensive shape.\n\nWeaknesses: Outnumbered in midfield against 3-man setups. Flat midfield struggles to shift quickly.\n\nHow to attack it as a midfielder:\n— Exploit the space BETWEEN their midfield and defensive line\n— Receive there and you have time\n— Overload one side then switch quickly\n— Thread through balls between the central mids" },
    { title: "4-3-3 — Possession & Press", content: "Four defenders. Three midfielders. Three forwards. Barcelona's formation.\n\nStrengths: Three forwards press high, triangles everywhere, wide forwards pin fullbacks.\n\nWeaknesses: Wide forwards must track back or you're exposed. Requires enormous fitness.\n\nHow to attack it:\n— Attack the space BEHIND pressing forwards\n— Switch play quickly — wide areas open with fast movement\n— Striker's movement pulls center backs, creating gaps for midfield runners" },
    { title: "4-2-3-1 — The Dominant Modern Formation", content: "Four defenders. Two defensive midfielders (double pivot). Three attacking mids. One striker.\n\nStrengths: Double pivot gives stability AND possession control. The #10 between the lines is extremely hard to defend. Flexible.\n\nWeaknesses: Lone striker isolated. Fullbacks often exposed.\n\nHow to attack it:\n— Flanks are vulnerable\n— A diamond midfield suffocates the double pivot\n— Quick counters before defensive shape reorganizes" },
    { title: "3-5-2 — Five In Midfield", content: "Three center backs. Two wing-backs. Three central midfielders. Two strikers.\n\nStrengths: Total midfield control, two strikers, extra defensive coverage.\n\nWeaknesses: Wing-backs cover enormous ground. Three center-backs overloaded by width.\n\nHow to attack it:\n— Push wing-backs back — remove their attacking contribution\n— Hit behind wing-backs with fast runs when they push forward\n— Play wide — stretch the three center-backs" },
    { title: "The Low Block — How To Break It", content: "Some teams just park. Nine or ten men behind the ball.\n\n1. Patience. They want you to rush.\n2. Move the ball quickly — short combinations force their shape to shift.\n3. Switch play FAST. Forces the entire block to move.\n4. Get wide and cross — numbers in the box can break it.\n5. Midfield runners arriving late are hard to track.\n6. Through ball into channels between last defender and the 18.\n\nWhat doesn't work: Individual dribbling into a packed defense." },
  ]},
  { id: "defending", title: "Defending", icon: "🛡️", subtitle: "Reading Players, 1v1, Pressure", sections: [
    { title: "The Fundamentals Of Individual Defense", content: "Defense starts before the attacker gets the ball.\n\nCore principles:\n1. Be goal-side. Always position between attacker and goal.\n2. Delay, don't dive. Buy time for teammates.\n3. Stay on your feet. Committed tackles that miss are gifts.\n4. Force a direction. Channel toward sideline or weak foot.\n5. Watch the ball, not the feet. Feints happen with the body. The ball tells the truth.\n\nThe jockeying position: Side-on stance, weight on back foot, low center of gravity." },
    { title: "Defending Fast Players", content: "Fast attackers need space to run into. Eliminate that space.\n\nHow to defend pace:\n1. Get tight EARLY — before they have the ball.\n2. Force them wide. The sideline is your teammate.\n3. Don't turn and chase. Focus on preventing the moment.\n4. Angle your run so they must go wide.\n5. Be physical early — fast players hate physicality.\n\nKey shift: You're not trying to win the ball. You're making them predictable." },
    { title: "Defending Technically Skilled Players", content: "A technically elite dribbler slows down and waits for you to commit.\n\nGolden rule: Do NOT lunge. They're waiting for it.\n\nHow to defend skill:\n1. Patience. Stand them up. Make them make the first move.\n2. Watch the ball, not the body.\n3. Force them onto their weak foot.\n4. Shrink their space — tight enough they can't turn.\n5. Tackle only when they take a heavy touch. Then commit fully." },
    { title: "Defending Physical Players", content: "Strong attackers try to back into you and use their body as a shield.\n\nPrinciples:\n1. Don't engage their back. Stay to the side.\n2. Arms-length positioning: Too close and they spin you. Too far and they turn.\n3. Be first to the ball.\n4. Use your body legally — shoulder to shoulder.\n5. Force wide. Physical strikers are most dangerous centrally." },
    { title: "The Art Of Pressing", content: "Pressing isn't chasing the ball. Uncoordinated pressing creates space.\n\nPress when:\n— Opponent receives with back to goal\n— They take a heavy first touch\n— Ball goes to a weak-footed player\n\nHow to press effectively:\n1. Know where you're forcing the ball BEFORE you press\n2. Cut off the easy pass\n3. Teammates must press in coordination\n4. Don't overcommit\n\nHigh press wins the ball high but is exhausting. Mid press is more sustainable." },
  ]},
  { id: "midfield", title: "The Midfielder", icon: "🧠", subtitle: "Positioning, Vision & The Isagi Principles", sections: [
    { title: "What Makes A Midfielder Elite", content: "The average player has direct possession for only 1–3 minutes in 90.\n\nWhat separates elite midfielders:\n1. Scanning frequency — Xavi scanned 0.83 times per second. Elite: 6–8 times in 10 seconds.\n2. Pre-decisions — By the time the ball arrives, the decision is already made.\n3. Body orientation — Always receive with an open body. 'Play the way you face.'\n4. Movement OFF the ball — Where you position without it determines what balls you get.\n5. Tempo control — Knowing when to play fast and when to slow down." },
    { title: "Scanning — The Skill That Separates Everyone", content: "Scanning is checking your shoulders to gather information BEFORE the ball arrives.\n\nHow to build the habit:\n— Force yourself to check both shoulders before every receive\n— Rule: never receive without at least one shoulder check\n— Target: scan every 3 seconds minimum\n\nWhat to look for:\n— Where is the nearest pressure?\n— Which teammate is open?\n— Where is the space?\n— What is the defensive shape?\n\nYou're taking a photograph of the field. File it instantly. Act on it." },
    { title: "Positioning Between The Lines", content: "The most dangerous position: the space between opponent's midfield and defensive line.\n\nWhy it's dangerous:\n— Midfielders can't press without leaving space behind\n— Defenders can't step out without exposing their line\n— You're facing goal with time and space\n\nHow to get there:\n— Move away from the ball to create angles\n— Time your run to arrive AS the ball is played\n\nThe half-space: Between center and wing. Where Iniesta, Modric, De Bruyne operate." },
    { title: "The Isagi Principles — Spatial Dominance", content: "Isagi's weapon isn't skill or pace — it's meta-vision.\n\n1. Before the ball arrives: where is the SPACE? Not the ball. The space.\n\n2. Predict where space will open: Fullback pushes forward → space opens behind. Read movement to predict the gap, then move there BEFORE it opens.\n\n3. Exploit the transition moment: The 3–5 seconds after possession changes. Strike in this window.\n\n4. Create space for others: Your run doesn't need to end in receiving. Dragging a defender away is a successful action.\n\n5. The chain calculation: Calculate two passes ahead before every touch." },
    { title: "First Touch — The Foundation Of Everything", content: "Your first touch tells everyone on the field who you are.\n\nTypes:\n— Cushion touch: Relax the surface to kill the ball's pace.\n— Directional touch: Redirect with inside or outside as it arrives.\n— First-time pass: The touch IS the pass. Requires pre-scanning.\n\nTraining: Wall work. Control it dead every time. Both feet. 100 reps each surface.\n\nThe test: After receiving, can you immediately look up? Still looking down = touch wasn't good enough." },
    { title: "Tempo — Controlling The Game's Pace", content: "Elite midfielders SET the rhythm.\n\nPlay FAST when:\n— Transition moments\n— Defenders are disorganized\n— A runner is making a timed run\n\nSlow DOWN when:\n— Team needs to reorganize shape\n— No forward option available\n— Pressing is coming\n\nMost common amateur mistake: Playing fast all the time. Top teams play slow to go fast.\n\nYou are the tempo dial. Own it." },
  ]},
  { id: "mental", title: "Mental Game", icon: "🔥", subtitle: "Psychology, Pressure & Domination", sections: [
    { title: "The Psychology Of Competition", content: "Soccer is played twice — once in the body, once in the mind.\n\nWhat separates competitive players:\n— Composure under pressure: Execute technique when heart rate is 160.\n— Short memory: Forget bad touches instantly.\n— Reading opponents: Frustrated? Apply more pressure. Confident? Disrupt their rhythm.\n\nThe composure principle: Your technique only holds under pressure to the level you've practiced it under pressure. Train at speed, under fatigue, with consequences." },
    { title: "Imposing Yourself Mentally", content: "It's not trash talk. It's actions that make opponents feel the game is already decided.\n\n1. Dominate the first five minutes: Win your first header, tackle, and pass.\n2. Visible composure: When you're calm and they're not, it communicates power.\n3. Physicality in legal spaces: Use it early.\n4. Punish every mistake instantly: Transition immediately when they give it away.\n5. Be unpredictable: Change your patterns. Make them feel like they can't read you." },
    { title: "Visualization — Training The Brain", content: "Your brain cannot fully distinguish between a vividly imagined action and a real one.\n\nHow to do it properly:\n1. Be specific. Visualize receiving under pressure, taking a directional touch, threading a through ball.\n2. All senses. See the field, hear the crowd, feel the ball.\n3. Include adversity. Visualize a bad touch — then recovering.\n4. Pre-match: 5–10 minutes before every game or session.\n\nFive minutes every night before sleep. It costs nothing. Over months, it compounds." },
    { title: "The Transition Mindset", content: "The most dangerous moment in soccer: the 3–5 seconds after possession changes.\n\nWhen you WIN the ball: Look forward immediately. Attack before the defense organizes.\n\nWhen you LOSE the ball: Counter-press immediately. Don't sulk. The ball is closest to your team in the moment just after losing it.\n\nYour profile — lean, fast, explosive — is perfectly suited to transition moments. This is where you are most dangerous." },
    { title: "Handling Mistakes & Staying In The Game", content: "The most consequential skill in soccer isn't technical. It's moving on instantly from errors.\n\nThe reset process:\n1. Accept: It happened. That's done.\n2. Analyze: Decision error or execution error? File it for later.\n3. Redirect: Where do I need to be RIGHT NOW?\n4. Go: Move. Don't stand still processing.\n\nThe whole process takes 2 seconds. Long memory is a liability in competition." },
  ]},
  { id: "iq", title: "Soccer IQ", icon: "📡", subtitle: "Reading The Game, Space & Time", sections: [
    { title: "Space — The Real Currency Of Soccer", content: "The ball is secondary. Space is the game.\n\nTypes of space:\n— Behind the defensive line: Most dangerous. Through ball here often leads to goal.\n— Between the lines: Where midfielders operate.\n— Wide space: Stretches defense, opens central areas.\n— Space created by movement: Running without the ball drags defenders.\n\nThe central question before every action: Where is the space, and how do I attack it or create it?" },
    { title: "Reading Defensive Shape", content: "Understanding how the opposition defends tells you exactly where to attack.\n\nHigh defensive line: Vulnerability — space in behind for pace.\nDeep defensive line: Vulnerability — space in front of defense.\nZonal defense: Attack by creating overloads.\nMan marking: Drags defenders out of position with intelligent movement.\n\nBefore every game: Watch how they defend for 10 minutes. Where do they give space? Which player is weakest?" },
    { title: "The Third Man Run", content: "Player A passes to Player B. Player B is marked. But A's pass was a TRIGGER — it signals Player C (the third man) to make a run into space.\n\nThe defender marking B watches the ball. The defender covering C's zone tracks the ball. Neither watches C's run until it's too late.\n\nHow to use it:\n1. Recognize when a teammate is about to play a pass\n2. Time your run so you arrive as the ball reaches the second player\n3. You receive in full stride with space ahead\n\nThis is Isagi's chain calculation in real soccer." },
    { title: "Overloads & Numerical Superiority", content: "Numerical superiority = more of your players than theirs in a specific area.\n\n2v1 anywhere = the defender cannot stop both. One of you is always free.\n\nHow midfielders create overloads:\n— Positional rotation: Move into areas with fewer defenders\n— Overlapping runs: Give and go. Pass, then run.\n— Third man combinations\n\nThe best midfielders manufacture overloads. Don't wait for them." },
    { title: "Transition — The Game Within The Game", content: "Modern soccer is increasingly about transitions.\n\nOffensive transition (just won the ball):\n— Look forward immediately\n— Attack before defense reorganizes\n— Exploit the 5-second window\n\nDefensive transition (just lost the ball):\n— Counter-press immediately\n— Sprint to defensive position\n— Delay their attack\n\nThe gegenpressing principle: Winning the ball back within 5 seconds is statistically the most dangerous way to create a goal-scoring opportunity. Your profile is perfectly suited to this." },
  ]},
];

const NAV_ICONS = {
  dashboard: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>`,
  training: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>`,
  bible: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>`,
  journal: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>`,
  tracker: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>`,
  goals: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>`,
  weakfoot: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18h6"/><path d="M10 22h4"/><path d="M15.09 14c.18-.98.65-1.74 1.41-2.5A4.65 4.65 0 0 0 18 8 6 6 0 0 0 6 8c0 1 .23 2.23 1.5 3.5A4.61 4.61 0 0 1 8.91 14"/></svg>`,
  vidnotes: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2"/></svg>`,
  skills: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>`,
  shots: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>`,
};

const navItems = [
  { id: "dashboard", label: "Home", icon: "dashboard" },
  { id: "training", label: "Training", icon: "training" },
  { id: "bible", label: "Bible", icon: "bible" },
  { id: "journal", label: "Journal", icon: "journal" },
  { id: "tracker", label: "Progress", icon: "tracker" },
  { id: "goals", label: "Goals", icon: "goals" },
  { id: "weakfoot", label: "Weak Foot", icon: "weakfoot" },
  { id: "vidnotes", label: "Videos", icon: "vidnotes" },
  { id: "skills", label: "Skills", icon: "skills" },
  { id: "shots", label: "Shots", icon: "shots" },
];